include make.common

# Ayuda de como generar makefiles: https://www3.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html

# Ejemplo1: \
	Muestra como wrapper una funcion sin argumentos y sin retorno
ejemplo1: src/hola_mundo/ejemplo1$(PYTHON_EXTENSION_SUFFIX) ;

# Ejemplo2: \
	Con un argumento, no funciona los argumentos por defecto	
ejemplo2: src/hola_mundo/ejemplo2$(PYTHON_EXTENSION_SUFFIX) ;

# Ejemplo3: \
	Con un argumento, si funciona los argumentos por defecto	
ejemplo3: src/hola_mundo/ejemplo3$(PYTHON_EXTENSION_SUFFIX) ;

# Ejemplo4: \
	Con un argumento, valor por retorno, si funciona los argumentos por defecto	
ejemplo4: src/hola_mundo/ejemplo4$(PYTHON_EXTENSION_SUFFIX) ;

# Ejemplo5: \
	Vector, ejercicio para wrappear la funcion
ejemplo5: src/vector/ejemplo5$(PYTHON_EXTENSION_SUFFIX) ;

# Ejemplo6: \
	Vector, primera aproximacion por medio de listas de python
ejemplo6: src/vector/ejemplo6$(PYTHON_EXTENSION_SUFFIX) ;

# Ejemplo7: \
	Vector, segunda aproximacion por medio de listas y array de numpy
ejemplo7: src/vector/ejemplo7$(PYTHON_EXTENSION_SUFFIX) ;

# Ejemplo8: \
	Vector, tercera aproximacion por medio de clases
ejemplo8: src/vector/ejemplo8$(PYTHON_EXTENSION_SUFFIX) ;

# Ejemplo9: \
	Vector, cuarta aproximacion por medio de registros
ejemplo9: src/vector/ejemplo9$(PYTHON_EXTENSION_SUFFIX) ;
	
